### ISSUE TITLE
Where do the docs live?

### ISSUE THREAD

**Issue by neonwatty** [stimulus-components/stimulus-components#100]
I'd like to fix a bug found in the docs - where do they live?  Apologies - didin't see them in this repo or the org - probably missed them.

**Comment by guillaumebriday** [comment]
Hey!

What kind of bug are you referring to? Are you perhaps looking for this link: https://github.com/stimulus-components/stimulus-components/tree/master/content/docs?

**Comment by neonwatty** [comment]
Thanks for the pointer!  Turns out the bug was in my brain.
