### ISSUE TITLE
stimulus-timeago: allow date-fns 4.x

### ISSUE THREAD

**Issue by tagliala** [stimulus-components/stimulus-components#118]
https://github.com/stimulus-components/stimulus-components/blob/ef922055a6a61737e6b8009755d6bb43d5f05e89/components/timeago/package.json#L34

**Comment by guillaumebriday** [comment]
Done ✅ 

Available in 5.0.2

See: https://github.com/stimulus-components/stimulus-components/commit/cda5eabbd11a0ec8d7db4107ea4030a8c6f56fec

Thanks for the suggestion!
