### ISSUE TITLE
Stimulus-components Logo

### ISSUE THREAD

**Issue by guillaumebriday** [stimulus-components/stimulus-components#12]
Anyone could make a good looking logo ? :pray:

**Comment by jgigault** [comment]
Is Microsoft Paint authorized as a tool for this item? 😄

**Comment by guillaumebriday** [comment]
Absolutely!! 😅

**Comment by thomasvanholder** [comment]
@guillaumebriday , are you still looking for a logo for Stimulus Components?

**Comment by guillaumebriday** [comment]
@thomasvanholder I am! :D

**Comment by thomasvanholder** [comment]
> @thomasvanholder I am! :D

Cool, Stimulus is just great and I love what you did with Stimulus Components. I've asked a friend of mine to create a couple of logos to show you next week. 

There's an article I've written about Stimulus Carousel. It'll be published next week on Medium. Here's a [draft link](https://medium.com/@thomasvanholder/build-a-carousel-with-ruby-on-rails-and-stimulus-components-22b1b5e1e682) for it.

**Comment by thomasvanholder** [comment]
@guillaumebriday, anything you like? If you prefer a different style or medication, I can always return to the designer.

![1Color-strong-font](https://user-images.githubusercontent.com/36309895/106365147-83bedf80-632b-11eb-9c1c-29a9acd5e3fb.jpg)
![2color](https://user-images.githubusercontent.com/36309895/106365148-84f00c80-632b-11eb-98b9-ea96dc1f9fc1.jpg)
![2diffcolorandfont](https://user-images.githubusercontent.com/36309895/106365149-86213980-632b-11eb-9dd4-e1e464c723c5.jpg)
![2nocolor](https://user-images.githubusercontent.com/36309895/106365150-87526680-632b-11eb-9103-20f69e6981fa.jpg)
![No color different font](https://user-images.githubusercontent.com/36309895/106365151-87eafd00-632b-11eb-8780-e37fd5f1ca6b.jpg)
![Stimulus orange ](https://user-images.githubusercontent.com/36309895/106365152-87eafd00-632b-11eb-80b1-12031ee10285.jpg)

**Comment by thomasvanholder** [comment]
@guillaumebriday, are there any of the logos you like, or will you look for something else? If you like them, I can send them to you in high resolution.

**Comment by benkoshy** [comment]
LGTM. Even if you pick one at random, it would still be winning. I do fancy the first one.
