### ISSUE TITLE
Calendar/Date/Time/Schedule

### ISSUE THREAD

**Issue by danieldraper** [stimulus-components/stimulus-components#21]
An example from Asana (others obviously exist)

![image](https://user-images.githubusercontent.com/1016423/98815746-57ee3500-2473-11eb-808d-2db1a35dc62a.png)
![image](https://user-images.githubusercontent.com/1016423/98815798-6ccac880-2473-11eb-8a80-049ab404a023.png)
![image](https://user-images.githubusercontent.com/1016423/98815816-72281300-2473-11eb-9646-ad4f98744065.png)
![image](https://user-images.githubusercontent.com/1016423/98815828-76543080-2473-11eb-81be-17651945fea1.png)

**Comment by guillaumebriday** [comment]
Hey, what about this one: https://github.com/adrienpoly/stimulus-flatpickr?
