### ISSUE TITLE
Google Tag Manager controller

### ISSUE THREAD

**Issue by michaelbaudino** [stimulus-components/stimulus-components#22]
Adding Google Tag Manager on a website is pretty much:
1. an initializer:
    ```html
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-XXXX');</script>
    <!-- End Google Tag Manager -->
    ```
2. a bunch of objects pushed into a global array on user events:
    ```html
    <a href="…" onClick="dataLayer.push({'event': 'someUserAction', someContext: 'whateverYouWant'})">…</a>
    ```

I'm pretty sure there's a way to do this using Stimulus, with something like:

```html
<a href="…" data-controller="gtm" data-gtm-event="someUserAction" data-gtm-some-context="whateverYouWant">…</a>
```

I'm not sure how initialization could be done in a DRY-manner, though :thinking: 
And I'm not sure whether the Stimulus version is actually more or less readable than the `onClick` version :sweat_smile: 
But you know, I'm just brain-dumping some use-cases…

**Comment by guillaumebriday** [comment]
Thanks for the idea

Check this repo : https://github.com/stimulus-components/stimulus-gtm
