### ISSUE TITLE
In Place Edit

### ISSUE THREAD

**Issue by crispincornett** [stimulus-components/stimulus-components#23]
What do you think about adding an in place editing solution a-la the old jQuery based [Best in Place](https://github.com/bernat/best_in_place) gem and the Bootstrap based [X-editable](https://vitalets.github.io/x-editable/).

**Comment by guillaumebriday** [comment]
I think you can do it with https://github.com/stimulus-components/stimulus-popover right?

**Comment by ocarreterom** [comment]
Maybe with https://github.com/stimulus-components/stimulus-reveal-controller
