### ISSUE TITLE
Autoremove controller

### ISSUE THREAD

**Issue by guillaumebriday** [stimulus-components/stimulus-components#24]

**Comment by seanfcarroll** [comment]
What's an autoremove controller?

Awesome project BTW, thank you.

**Comment by guillaumebriday** [comment]
Thanks @seanfcarroll 

A controller that remove the element from the dom after a given amount of time

Very basic, but useful for notification for instance

**Comment by seanfcarroll** [comment]
Ah cool @guillaumebriday in fact we will soon code a StimulusJS controller to slide up & remove a Rails flash message. Perhaps we could contribute it back here?

**Comment by guillaumebriday** [comment]
That would be great! In fact, I was waiting this PR (https://github.com/stimulus-use/stimulus-use/pull/77) to be merged before starting this controller and doing animation myself.

**Comment by seanfcarroll** [comment]
https://github.com/stimulus-use/stimulus-use/pull/77 looks pretty good!

**Comment by adrienpoly** [comment]
👋  @guillaumebriday @seanfcarroll I plan to merge `useTransition` next week. I had to play a bit with the API first and look into the different edge cases.

**Comment by guillaumebriday** [comment]
I'm so hyped, I'll use it basically everywhere!

**Comment by guillaumebriday** [comment]
Here we go https://github.com/stimulus-components/stimulus-notification
