### ISSUE TITLE
Password Controller

### ISSUE THREAD

**Issue by tsdevelopment** [stimulus-components/stimulus-components#30]
I think we need another controller to show / hide passwords in password fields.

**Comment by tsdevelopment** [comment]
I wrote a small example how this could work:
https://codepen.io/pen/ZEBLvLW

**Comment by guillaumebriday** [comment]
There we go: https://github.com/stimulus-components/stimulus-password-visibility

Sorry @tsdevelopment I completely forgot your example! Tbh I really love your idea with `this.buttonTargets`.

Will maybe add it later!

Thanks!

**Comment by guillaumebriday** [comment]
Just changed it in fact: https://github.com/stimulus-components/stimulus-password-visibility/commit/d34757f9f122ee76f7c570496c7d286f4dcc477a
