### ISSUE TITLE
Improve link color contrast

### ISSUE THREAD

**Issue by ocarreterom** [stimulus-components/stimulus-components#32]
I notice that the links color have a poor contrast and it is a little hard to read. Making it a darker can help.

https://coolors.co/contrast-checker/f59e0b-ffffff
https://coolors.co/contrast-checker/f59e0b-f5f6fa

**Comment by guillaumebriday** [comment]
You're right, thanks for reporting it! 🙏 

I try to change for that https://coolors.co/contrast-checker/e27618-ffffff

I'm clearly not an expert but it's a bit better. I have no idea how to keep the orange with a good contrast tbh.

**Comment by ocarreterom** [comment]
Yes, it seems difficult to get the contrast with orange. 😅 
Something like this? 🤷‍♂️
`#CC4E00`  https://coolors.co/contrast-checker/cc4e00-ffffff

<table>
  <tr>
    <td>Before (3.07)
    <td>After (4.51)
  <tr>
    <td><img width="491" alt="Captura de pantalla 2021-08-02 a las 11 14 28" src="https://user-images.githubusercontent.com/11599942/127836566-9a1e9039-4a2a-416f-b201-cee813aa7694.png">
    <td><img width="467" alt="Captura de pantalla 2021-08-02 a las 11 14 36" src="https://user-images.githubusercontent.com/11599942/127836606-73a876bb-7b17-4735-ad63-22829b3ed7ba.png">
</table>

**Comment by guillaumebriday** [comment]
Thanks @ocarreterom 🙏
