### ISSUE TITLE
Great Job

### ISSUE THREAD

**Issue by seb-jean** [stimulus-components/stimulus-components#34]
Congratulations to what you are doing Guillaume !
It's great to have created Stimulus components and added more :rocket:.
Thank you.

-----

Bravo à ce que tu fais Guillaume !
C'est super d'avoir créer des composants Stimulus et d'en ajouter d'autres :rocket:.
Merci.

**Comment by guillaumebriday** [comment]
Thank you @seb-jean 🙏
