### ISSUE TITLE
Failed to resolve module specifier Rails 7.0 (All components)

### ISSUE THREAD

**Issue by sergitejada** [stimulus-components/stimulus-components#48]
I am trying to use the components following the documentation 
1. I install the package of the component I want with `yarn`.
2. In my `app/javascript/controllers/index.js` file I add the component as described in the documentation.

![image](https://user-images.githubusercontent.com/49126831/168857714-5aa1e757-e02b-4fa6-a886-1f41a05143f1.png)

Error displayed by the browser
`Uncaught TypeError: Failed to resolve module specifier "stimulus-autocomplete". Relative references must start with either "/", "./", or "../".`

I have found people with my same problem that solved it with a package call to a yarn cdn, I think it makes no sense to call a cnd with the code when the code is in local. 

[Error-1](https://stackoverflow.com/questions/71489694/failed-to-resolve-module-specifier-stimulus-autocomplete)
[Error-2](https://stackoverflow.com/questions/72142193/how-to-use-stimulus-components-with-rails-import-maps/72277291#72277291)

ruby "2.7.0"
rails "7.0.2"

**Comment by inspire22** [comment]
Did you ever solve this?  I'm trying to migrate my rails 7 app from sprockets to importmaps and am getting a similar error, I believe rails isn't properly using the importmap for some reason to figure out where to load the packages from, but can't figure out where to look next.

**Comment by hieunguyentrung** [comment]
@inspire22 
You can try this way

1. Import `stimulus-dropdown`
```
./bin/importmap pin stimulus-dropdown
```
2. Append the following lines to your controller
```
import { application } from "controllers/application"; # Remove this line if you are appending to application.js

import ContentLoader from 'stimulus-content-loader'

application.register('content-loader', ContentLoader)

```

**Comment by guillaumebriday** [comment]
Same as https://github.com/stimulus-components/stimulus-components/issues/81#issuecomment-2027343664
