### ISSUE TITLE
Toggle Element controller

### ISSUE THREAD

**Issue by johnnynia** [stimulus-components/stimulus-components#58]
Just a simple controller to toggle elements outside the scope of the controller itself. 
```js
import { Controller } from '@hotwired/stimulus'


export default class extends Controller {
  static classes = ['hidden']

  static values = {
    id: String,
  }

  initialize() {
    this.class = this.hasHiddenClass ? this.hiddenClass : 'hidden'
  }

  connect() {
    this.element.addEventListener('click', this.toggle)
  }

  disconnect() {
    this.element.removeEventListener('click', this.toggle)
  }

  toggle = () => {
    const element = document.getElementById(this.idValue)
    if (element) {
      element.classList.toggle(this.class)
    }
  }
}

```
```html
<button type="button" data-controller="toggle-element" data-toggle-element-id-value="menu">
  Toggle menu.
</button>

<div>…</div>

<nav id="menu"></nav>
```
Maybe this could be useful for others too. I'm not sure about the naming though. (And a selector instead of an id could possibly make more sense.) What do you think?

Btw. thank you for this project; It helped me a lot in understanding stimulus! ❤️

**Comment by guillaumebriday** [comment]
Hey @johnnynia thanks for your comments

It seems very similar to https://www.stimulus-components.com/docs/stimulus-reveal-controller right?

**Comment by johnnynia** [comment]
Yes, it's very similar to the existing Reveal Controller. It just solves the problem of toggling an element out of the controller's scope. Feel free to close this if you think it's too redundant. :-)

**Comment by guillaumebriday** [comment]
Yep I think it's really for your specific use case 👍 
Thanks for the suggestion though
