### ISSUE TITLE
stimulus-timeago: Rails helper

### ISSUE THREAD

**Issue by basicfeatures** [stimulus-components/stimulus-components#64]
Hello!

Any idea why the `stimulus-timeago` Rails helper doesn't seem to work with any of the locales in say https://github.com/svenfuchs/rails-i18n/?

```
def timeago(date, format: :long)
  return if date.blank?

  content = I18n.l(date, format: format)

  tag.time(content,
            title: content,
            data: {
              controller: 'timeago',
              timeago_datetime_value: date.iso8601
            })
end

[...]

<p>Created <%= timeago(@project.created_at) %></p>
```

I get English despite having set a different locale with `I18n.locale` in my application controller.

Thanks!

**Comment by guillaumebriday** [comment]
Hi @basicfeatures 

The Rails locale is not used in the JavaScript,

You need to import it in the stimulus controller as it is explained in the `Extending Controller` section of the documentation https://www.stimulus-components.com/docs/stimulus-timeago

**Comment by basicfeatures** [comment]
I see, cool thanks for letting me know. I have some 10-20 different locales though so I think in my case it'll be easier to just stick to the standard Rails way.

Cheers!
