### ISSUE TITLE
issue with encoding

### ISSUE THREAD

**Issue by Chris-pyz** [stimulus-components/stimulus-components#66]
When I copy-paste with stimulus-clipboard, the "&" character it returns its HTML code to the clipboard (&amp) , it does that too with <  and > (&lt and &gt)

I don't have this problem with a right click then copy-paste.

**Comment by guillaumebriday** [comment]
Are you sure the characters in the code are not already escaped too?

**Comment by guillaumebriday** [comment]
Reopen if needed 👍
