### ISSUE TITLE
skeleton for new component?  Or a github repo template?

### ISSUE THREAD

**Issue by tacman** [stimulus-components/stimulus-components#75]
I have a small stimulus component I'd like to contribute, as I find it very useful in my own code.  It displays languages and countries from their respective ISO codes, saving the user from needing to do the lookup in the server code.

Is there a skeleton for the component repository?  The components here seem to all be in TypeScript, I can convert it.  But the documentation and such should all be standardized.  If there's a skeleton that already exists, I'd love to use it.

Also, what's the procedure for doing this?  I can create a repo for testing and such, then move it to here?  I'd also like some feedback on my implementation, especially naming the attributes, and even naming the component.  

The code itself isn't that complicated, I can also paste it here, since it's just one file.

**Comment by guillaumebriday** [comment]
Hey! Thanks for the suggestion.

At the moment I don't have a proper skeleton to create a new controller because it does not happen really often. But what about duplicate one on your personal account and then add it with Stimulus Components once ready?

**Comment by guillaumebriday** [comment]
There you go: https://github.com/stimulus-components/stimulus-skeleton

thanks

**Comment by tacman** [comment]
Thanks!  The link to the docs is broken: https://www.stimulus-components.com/docs/stimulus-skeleton/

Also, can you expand a bit on "# 5. Create the Netlify site."

Certainly there are ways to automate some of these steps.  Even 'sed' might work for the replacement steps.

I have a simple, but within my apps very useful, stimulus component displays country and language names in the current (or configured) locale.  It saves me from needing to use server functions like Symfony's intl library and render it on the server.  

So if I wanted to submit it here, I could follow these steps, but the majority of the files will be empty or whatever the skeleton defaults are.  Should the empty ones be deleted?

**Comment by guillaumebriday-pa** [comment]
It is broken it's not a real component already, you are supposed to change the name according to the component your are currently working on 👍 

Can you share a gist with the code of your controller so I can see it before adding it to the lib?

Thanks!

**Comment by tacman** [comment]
```javascript
import {Controller} from '@hotwired/stimulus';

// @todo, add days of week and month names: https://stackoverflow.com/questions/39972925/get-localized-month-name-using-native-js

/*
* The following line makes this controller "lazy": it won't be downloaded until needed
* See https://github.com/symfony/stimulus-bridge#lazy-controllers
*/
/* stimulusFetch: 'lazy' */
export default class extends Controller {
    static targets = ['country', 'language']
    static values = {
        userLocale: String,
    }

    // ...
    initialize() {
        this.regionNames = new Intl.DisplayNames(
            [this.userLocaleValue], {type: 'region'}
        );
        this.languageNames = new Intl.DisplayNames(
            [this.userLocaleValue], {type: "language"});

    }

    connect() {

        if (this.hasLanguageTargets) {
            this.languageTargets.foreach((t) => {
                    let languageCode = t.dataset.lang;
                    t.innerHTML = 'testing...' + languageCode; //  +  this.regionNames.of('MX');
                }
            );

        } else {
            // console.error('no language targets in ' + this.identifier);
        }

    }

    countryTargetConnected(element) {
        let countryCode = element.dataset.cc;
        element.innerHTML = this.regionNames.of(countryCode.toUpperCase());
    }

    languageTargetConnected(el) {
        let languageCode = el.dataset.lang;
        if (languageCode === undefined) {
            console.error('missing data-lang in target');
            return;
        }

        console.warn(languageCode);
            var x = this.languageNames.of(languageCode);
            if (x === undefined) {
                console.error( "Invalid languageCode code " + languageCode);
            } else {
                el.innerHTML = x;
            }
        try {
        } catch (error) {
            console.error(error, languageCode);
        }
    }


}
```

Within twig

```twig
    {% set _sc = 'locale_display' %}
{#    <div {{ stimulus_controller('intl', {userLocale: app.locale, country: owner.countryCode|upper }) }}></div>#}
    <div {{ stimulus_controller(_sc, {userLocale: app.locale, country: owner.countryCode|upper }) }}>
{#        <span {{ stimulus_target(_sc, 'language') }}>#}
{#            {{ owner.locale }}#}
{#        </span>#}

        <span {{ stimulus_target(_sc, 'country') }} data-cc="{{ owner.countryCode }}">
            replaced
        </span>

    </div>

```

So instead of {{ project.locale|language_name }}, which requires both being on the server and installing an extra extension, I can simply call the stimulus controller.

https://twig.symfony.com/doc/3.x/filters/language_name.html

**Comment by tacman** [comment]
Right!  But it's on the webpage, so you could add a link to the
installation instructions there.
