### ISSUE TITLE
Stimulus Controller import dependency

### ISSUE THREAD

**Issue by lubomirblazekcz** [stimulus-components/stimulus-components#80]
Hello, I've run into a minor issue. I'm loading Stimulus via await so it's separated from the bundle.  But `stimulus-components` imports stimulus directly so there is a conflict during build.

Would be possible to introduce class mixin without without depedency in your stimulus components? You would have more freadom how to import them into your projects.  Eg.

Current
```js
import { Application } from '@hotwired/stimulus'
import ScrollReveal from 'stimulus-scroll-reveal'

const application = Application.start()
application.register('scroll-reveal', ScrollReveal)
```

Proposed alternative
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/extends#mix-ins
```js
const { Application, Controller} = await import('@hotwired/stimulus')
const { registerScrollReveal } = await import('stimulus-scroll-reveal')

const application = Application.start()
application.register('scroll-reveal', registerScrollReveal(Controller))
```
```js
export const registerScrollReveal = Controller => {
    return class extends Controller {
        // code
    }
}
```

You could introduce alternative approach in separate file to leave a backward compatibility, `index.ts` would have only the register mixin with stimulus controller and these who would want to import dynamically would use something like `stimulus-scroll-reveal/mixin` or something like that.

**Comment by guillaumebriday** [comment]
Interesting! I've never heard about that actually!

I'm curious, what bundler do you use? And why would you need to use await in your import in the first place?  I never had to do that tbh

**Comment by lubomirblazekcz** [comment]
I'm using Vite, and when top level await is used it will automatically split the import into a chunk js. So the final bundle is split into smaller js files. 

But now when I think about it, this can be also done manually with regular import in the vite or rollup config.

So this might do the same trick without any change needed 👍
