### ISSUE TITLE
Documentation for importmaps

### ISSUE THREAD

**Issue by n-at-han-k** [stimulus-components/stimulus-components#81]
Most libraries list a way to install their packages using yarn or npm, but very little show installation using the new rails importmaps.
I know it’s a small change to documentation but adding it definitely finishes it off.

I’m happy to do the work and submit the pull requests if this is something you’d be happy to accommodate.
If the answer is no, please close this ticket.

**Comment by guillaumebriday** [comment]
We do have this page on the documentation to describe how to use importmaps with rails: https://www.stimulus-components.com/docs/installation but you're right, we could add a link or tabs like Nuxt does here: https://nuxt.com/docs/getting-started/installation so you can chose your installation method properly

I'll dive into it! 👍

**Comment by tchiadeu** [comment]
Not sure if this is the good place to write this but, for me, using importmap for 'lightbox' doesn't work.
When follow the installation for this stimulus component, we have this :
`// In your application.js (for example)
import 'lightgallery/css/lightgallery.css'

// Or in your sass
@import '~lightgallery/scss/lightgallery'`

But, the css files & assets doesn't exist if we use the impormap method.

I don't know how to fix this properly (I duplicate the css manually), so I'm just reported this problem.

**Comment by n-at-han-k** [comment]
I had a similar issue with `stimulus-color-picker`. I had to replace
```sass
@import '~@simonwep/pickr/dist/themes/classic.min.css'
```
with
```sass
@import url('https://cdn.jsdelivr.net/npm/@simonwep/pickr/dist/themes/classic.min.css')
```

Try adding lightbox with the code below.
```sass
@import url(‘https://cdn.jsdelivr.net/npm/lightgallery@2.7.2/css/lightgallery.css’)
```

**Comment by tchiadeu** [comment]
I have already resolve the problem as I said before but this is a better solution. Thanks

Didn't try yet but I think it will not found the fonts & the image (which is a loading gif) if we go for this one.
So elements that use the fonts (I think this is all the svg, so the arrows, dowload button...) will not be displayed as it would have to be.
