### ISSUE TITLE
Date adapter issue with Chartjs

### ISSUE THREAD

**Issue by jclusso** [stimulus-components/stimulus-components#89]
I'm getting the following error. 

`This method is not implemented: Check that a complete date adapter is provided.`

I've tried add `import 'chartjs-adapter-luxon'` to an inheritted controller. This is also imported globally since we are using ChartJS without Stimulus Components currently. Not sure how to get around this error so we can use timeseries charts.

**Comment by guillaumebriday** [comment]
You gonna need to override the `connect` method in your own controller so you can modify the chartJS import and use plugins or adapters.

Reopen if needed 👍
