### ISSUE TITLE
Allow date-fns:^3

### ISSUE THREAD

**Issue by tacman** [stimulus-components/stimulus-components#90]
In the process of updating, I ran across this warning:

    [warning] stimulus-timeago requires date-fns@^2.29.3 but version 3.6.0 is installed.

**Comment by guillaumebriday** [comment]
I think it has been updated with the release of 5.0.0 👍 

And it's just a warning, you can still use it I guess

**Comment by tacman** [comment]
Now it's at 

stimulus-timeago requires date-fns@^2.29.3 but version 4.1.0 is installed.

Of course, it's just a warning, but it'd be nice to not see it.
