### ISSUE TITLE
Stimulus Chartjs not working

### ISSUE THREAD

**Issue by BaggioGiacomo** [stimulus-components/stimulus-components#97]
I've used this guide: `https://www.stimulus-components.com/docs/stimulus-chartjs/`

When I navigate to the page that is using the chart controller, I cannot see it.
I get this error on the console: `GET https://anchor-stress-across-mad.trycloudflare.com/dist/chart.js net::ERR_ABORTED 404 (Not Found)`. (`https://anchor-stress-across-mad.trycloudflare.com` is my app URL)

Network tab:
<img width="892" alt="image" src="https://github.com/user-attachments/assets/d3ce0b14-6ced-4b3b-807a-afce376db31e">

`importmap.rb` file contains:
```ruby
pin "@stimulus-components/chartjs", to: "@stimulus-components--chartjs.js" # @6.0.0
pin "@kurkle/color", to: "@kurkle--color.js" # @0.3.2
pin "chart.js/auto", to: "chart.js--auto.js" # @4.4.3
```

`app/javascript/controllers/index.js`:
```javascript
import { application } from "controllers/application";
import Chart from "@stimulus-components/chartjs";

// Eager load all controllers defined in the import map under controllers/**/*_controller
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading";
eagerLoadControllersFrom("controllers", application);
application.register("chart", Chart);
```

`chart_controller.js`:
```javascript
import { Controller } from "@hotwired/stimulus";
import Chart from "@stimulus-components/chartjs";

// Connects to data-controller="chart"
export default class extends Controller {
  connect() {}
}
```

What can be wrong with that?

P.S: The chart [live preview](https://stimulus-chart.stimulus-components.com/) is not working

**Comment by guillaumebriday** [comment]
It feels like you imported the controller twice, once in `application.register("chart", Chart);` and the other because try to override the controller.

But, in your `chart_controller.js` you extends the Chart Controller directly:

```ts
import Chart from '@stimulus-components/chartjs'

export default class extends Chart {
```

See: https://www.stimulus-components.com/docs/stimulus-chartjs



And you're right, the correct url is https://stimulus-chartjs.stimulus-components.com/ I'm going to fix it in the docs thanks!

**Comment by BaggioGiacomo** [comment]
Hi @guillaumebriday
thanks for the fast response!

Here's what I'm doing:
1. `bin/importmap pin @stimulus-components/chartjs`
This command adds these rows on the `importmap.rb` file:
```ruby
pin "@stimulus-components/chartjs", to: "@stimulus-components--chartjs.js" # @6.0.0
pin "@kurkle/color", to: "@kurkle--color.js" # @0.3.2
pin "chart.js/auto", to: "chart.js--auto.js" # @4.4.3
````

2. I register the controller on my application:
```ruby
# app/javascript/controllers/index.js 

import { application } from "controllers/application";
import Chart from "@stimulus-components/chartjs";

// Eager load all controllers defined in the import map under controllers/**/*_controller
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading";
eagerLoadControllersFrom("controllers", application);
application.register("chart", Chart);
```

3. Add the chart on my view:
```ruby
# app/views/variants/show.html.erb

... some code

<canvas
  data-controller="chart"
  data-chart-data-value='{ "labels": ["January", "February", "March", "April", "May", "June", "July"], "datasets": [{ "label": "My First dataset", "backgroundColor": "transparent", "borderColor": "#3B82F6", "data": [37, 83, 78, 54, 12, 5, 99] }] }'
></canvas>
```


The chart is not showing and I get these error on the console:
<img width="951" alt="image" src="https://github.com/user-attachments/assets/65093980-0f03-4a57-bb6b-4994758960f9">

Is it possible that I get these error because I'm inside a frame? I'm creating a Shopify embedded app using only Rails (+ hotwire and turbo)

**Comment by guillaumebriday** [comment]
Fixed by https://github.com/stimulus-components/stimulus-components/pull/117
